debug: true

server:
  host: "0.0.0.0"
  port: "9100"

mongodb:
  host: "47.99.56.228"
  port: "27017"
  user: ""
  passwd: ""
  dbname: "blog"

redis:
  host: "47.99.56.228"
  port: ""
  passwd: ""
  db: 6

auth:
  mongodb:
    host: "47.99.56.228"
    port: "27017"
    user: ""
    passwd: ""
    dbname: "testrole"
  redis:
    host: "47.99.56.228"
    port: ""
    passwd: ""
    db: 10

